<?php
//Drupal.
function xoxo_components_block_info() {
  $l = 'Products';
  return array('products' => array('info' => t($l)));
}
//Block.
function xoxo_components_block_view($delta = '') {
  $block = array();
  if ($delta == 'products') {
    module_load_include('inc', 'xoxo_week', 'xoxo_week');
    $bid = _xoxo_first_field_value(arg(1), 'field_brand_id');
    $q = _xoxo_components_on_brand_page(_xoxo_search_nids_query(FALSE, $bid))
      ->range(0, variable_get('xoxo_components_products_limit', 7));
    $q->addField('n', 'nid');
    $nodes = node_load_multiple($q->execute()->fetchCol());
    $block['content'] = array(
      '#type' => 'container',
      '#attributes' => array('class' => array('products'))
    );
    foreach ($nodes as $node) {
      $block['content'][$node->nid] = node_view($node, 'in_brand_page');
    }
  }
  return $block;
}
function xoxo_components_block_configure($delta = '') {
  $f = array();
  if ($delta == 'products') {
    $vals = range(4, 100);
    $f['xoxo_components_products_limit'] = array(
      '#type' => 'select',
      '#title' => t('Limit'),
      '#options' => array_combine($vals, $vals),
      '#default_value' => variable_get('xoxo_components_products_limit', 7)
    );
    $f['xoxo_components_products_link'] = array(
      '#type' => 'link',
      '#href' => 'admin/structure/types/manage/component/display/in_brand_page',
      '#title' => t('Single product output settings.')
    );
  }
  return $f;
}
function xoxo_components_block_save($delta = '', $edit = array()) {
  if ($delta == 'products') {
    variable_set('xoxo_components_products_limit', $edit['xoxo_components_products_limit']);
  }
}
//Query.
function _xoxo_components_on_brand_page($query) {
  $name = 'brand_page';
  global $user;
  $query->join('flag_content', 'flag', 'n.nid=flag.content_id');
  $query->join('flags', 'flags', 'flags.fid=flag.fid');
  $query->condition('flags.name', $name);
  return $query;
}
