<?php
define('XOXO_FIELDS_PRODUCT', 'Product');
define('XOXO_FIELDS_DESCRIPTION', 'Description');
define('XOXO_FIELDS_BRAND', 'Brand');
define('XOXO_FIELDS_AMOUNT', 'How Much');
define('XOXO_SHL_ITEMS_FIELD', 'field_shopping_list_items');
define('XOXO_SHL_DATE_FIELD', 'field_shopping_list_date');
define('XOXO_FIELDS_EVENT_STATUSES_FIELD', 'field_event_statuses');
define('XOXO_FIELDS_CATEGORY', 'Category');
define('XOXO_COMPONENT_CAT_TID_FIELD', 'field_component_category');
define('XOXO_COMPONENT_CAT_3_TID_FIELD', 'field_component_category_3');
define('XOXO_COMPONENT_BRAND_FIELD', 'field_component_brand');
define('XOXO_BRANDS', 'xoxo_brands');
define('XOXO_NAMES', 'xoxo_names');
define('XOXO_FIELDS_MEAL_TYPE', 'field_recipe_meal_type');
define('XOXO_FIELDS_MEAL_TYPE_C', 'field_componets_meal_type');
define('XOXO_FIELDS_STAPLE_CAT', 'field_component_sc');
define('XOXO_FIELDS_PREP_MEAL', 'field_component_status');
define('XOXO_FIELDS_KIT_SET', 'field_component_ks');
define('XOXO_FIELDS_DATE', 'field_shopping_list');
define('XOXO_FIELDS_TYPE_COMPONENT', 'component');
define('XOXO_FIELDS_TYPE_RECIPE', 'recipe');
define('XOXO_FIELDS_TYPE_SHOPPING_LIST', 'shopping_list');
define('XOXO_FIELDS_PRESET_CALENDAR', 'calendar');
define('XOXO_FIELDS_PRESET_SHOPPING_LIST', 'shopping_list');
define('XOXO_FIELDS_EVENT_ITEMS_FIELD', 'field_event_recipes');
define('XOXO_FIELDS_COMPONENT_UOM_FIELD', 'field_component_uom');
define('XOXO_FIELDS_COMPONENT_QTY_FIELD', 'field_component_size');
define('XOXO_FIELDS_RECIPE_INGREDIENTS_FIELD', 'field_recipe_ingredients');
define('XOXO_FIELDS_COMPONENT_NAME_FIELD', 'field_component_name');
define('XOXO_FIELDS_UOM_VID', 4);
define('XOXO_FIELDS_DAYD_DATE', 'field_day_description_date');
define('XOXO_FIELDS_DAYD_TEXT', 'field_day_description_text');
define('XOXO_FIELDS_EVENT_TYPE_BREAKFAST', 138);
define('XOXO_FIELDS_EVENT_TYPE_LUNCH', 139);
define('XOXO_FIELDS_EVENT_TYPE_DINNER', 140);
define('XOXO_FIELDS_EVENT_TYPE_ADDITIONAL', 141);
define('XOXO_FIELDS_EVENT_TYPE_BREAKFAST_LABEL', 'Breakfast');
define('XOXO_FIELDS_EVENT_TYPE_LUNCH_LABEL', 'Lunch');
define('XOXO_FIELDS_EVENT_TYPE_DINNER_LABEL', 'Dinner');
define('XOXO_FIELDS_EVENT_TYPE_ADDITIONAL_LABEL', 'Additional');
define('XOXO_FIELDS_NEWLINE', '<br/>');
define('XOXO_FIELDS_SEP', ', ');
define('XOXO_FIELDS_LEN', '90');
define('XOXO_FIELDS_END', '…');
define('XOXO_FIELDS_MEAL_TO_EVENT_DEPENDANCIES',
        serialize(
          array(
            142 => 138,
            144 => 140,
            143 => 139,
            'default' => 141,
          )
        )
);
